FROM mcr.microsoft.com/mssql/server:2022-latest

USER root
RUN apt-get update && apt-get install mssql-tools
ENV ACCEPT_EULA Y
ENV MSSQL_PID Developer
ENV MSSQL_SA_PASSWORD CSFDcode123
ENV VTRVS_PASSWORD CSFDcode123

RUN mkdir /usr/init
COPY ./entrypoint.sh /usr/init/
COPY ./build.sh /usr/init/
COPY ./setup.sql /usr/init/
RUN chmod +x /usr/init/entrypoint.sh
RUN chmod +x /usr/init/build.sh
RUN chmod +x /usr/init/setup.sql

USER mssql
EXPOSE 1433

CMD /bin/bash /usr/init/entrypoint.sh