CREATE DATABASE nimbus;
GO
USE nimbus;
GO
CREATE LOGIN nimbus WITH PASSWORD='$(VTRVS_PASSWORD)';
GO
CREATE USER nimbus FOR LOGIN nimbus;
GO
CREATE SCHEMA lookup;
GO
GRANT ALTER, SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SCHEMA::dbo TO nimbus;
ALTER AUTHORIZATION ON SCHEMA::lookup TO nimbus;
GO
GRANT CREATE TABLE TO nimbus;
GO


