CREATE DATABASE vitruvius;
GO
USE vitruvius;
GO
CREATE LOGIN vitruvius WITH PASSWORD='$(VTRVS_PASSWORD)';
GO
CREATE USER vitruvius FOR LOGIN vitruvius;
GO
CREATE SCHEMA lookup;
GO
GRANT ALTER, SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SCHEMA::dbo TO vitruvius;
ALTER AUTHORIZATION ON SCHEMA::lookup TO vitruvius;
GO
GRANT CREATE TABLE TO vitruvius;
GO


