FROM python:3.11-slim

RUN mkdir /app
WORKDIR /app
ADD nodes/nimbus_config/model/ .

RUN apt-get update
RUN pip install -r requirements.txt

EXPOSE 5556

CMD [ "python3", "-m" , "flask","--app", "app:create_app()", "run", "--host=0.0.0.0", "--port=5556"]