FROM python:3.11-slim-buster

RUN mkdir /app
WORKDIR /app
ADD nodes/nimbus_develop/dev/ .

RUN pip install -r requirements.txt

EXPOSE 5552

CMD [ "python3", "-m" , "flask","--app", "app:create_app()", "run", "--host=0.0.0.0", "--port=5552"]