CREATE DATABASE vitruvius;
\c vitruvius;
CREATE USER vitruvius WITH PASSWORD '$(VTRVS_PASSWORD)';
GRANT ALL PRIVILEGES ON DATABASE vitruvius TO vitruvius;
CREATE SCHEMA lookup;
GRANT USAGE, CREATE ON SCHEMA lookup TO vitruvius;
ALTER DEFAULT PRIVILEGES IN SCHEMA lookup GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO vitruvius;
ALTER DEFAULT PRIVILEGES IN SCHEMA lookup GRANT USAGE, SELECT ON SEQUENCES TO vitruvius;
ALTER SCHEMA lookup OWNER TO vitruvius;
GRANT CREATE ON DATABASE vitruvius TO vitruvius;

